name: Render

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  attestations: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v5
      - name: Install fonts
        run: |
          echo 'Installing Noto Sans CJK...'
          sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra

          echo 'Installing Source Han Serif SC...'
          wget -O /tmp/09_SourceHanSerifSC.zip https://github.com/adobe-fonts/source-han-serif/releases/download/2.003R/09_SourceHanSerifSC.zip
          mkdir -p /tmp/09_SourceHanSerifSC
          unzip -o /tmp/09_SourceHanSerifSC.zip -d /tmp/09_SourceHanSerifSC
          sudo install -vDm644 -t /usr/share/fonts/opentype/source-han-serif-sc /tmp/09_SourceHanSerifSC/OTF/SimplifiedChinese/*.otf
          rm -rf /tmp/09_SourceHanSerifSC*

          echo 'Installing FontAwesome 7.2.0...'
          wget -O /tmp/fontawesome-free-7.2.0-desktop.zip https://use.fontawesome.com/releases/v7.2.0/fontawesome-free-7.2.0-desktop.zip
          unzip -o /tmp/fontawesome-free-7.2.0-desktop.zip -d /tmp
          sudo install -vDm644 -t /usr/share/fonts/opentype/fontawesome /tmp/fontawesome-free-7.2.0-desktop/otfs/*.otf
          rm -rf /tmp/fontawesome-free-7.2.0-desktop*

          echo 'Refreshing font cache...'
          sudo fc-cache -f -v
      - name: Render
        run: make dist
      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: '${{ github.workspace }}/dist/**/*'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4
        id: deployment
